name: Apply

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting up GCP environment
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: "${{ secrets.BODLEIAN_PROJECT_ID }}"
          service_account_key: "${{ secrets.GCR_SA_KEY }}"
          export_default_credentials: true   
      - name: Setup Terraform  
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init  
        run: terraform init   
      - name: Terraform Apply  
        run: terraform apply --auto-approve
        env:
          TF_VAR_codacy_api_token: "${{ secrets.BODLEIAN_CODACY_API_TOKEN }}"
          TF_VAR_project_id: "${{ secrets.BODLEIAN_PROJECT_ID }}"
          TF_VAR_docker_registry_username: "${{ secrets.DOCKER_REGISTRY_USERNAME }}"
          TF_VAR_docker_registry_token: "${{ secrets.DOCKER_REGISTRY_TOKEN }}"
          TF_VAR_target_repository_name: "koenighotze/bodleian"