name: Apply

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform  
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init  
        run: terraform init      
      - name: Terraform Apply  
        run: terraform apply --auto-approve